version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/ItemsPlanning.Pn"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.122
    - 2.0.127
    - 2.1.2
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.20
    - 4.4.22
    - 4.4.31
    - 4.4.36
    - 4.4.6
    - 4.4.7
    - 4.5.2
  - dependency-name: Magick.NET-Q16-x64
    versions:
    - 7.23.2.1
    - 7.23.3
    - 7.23.4
  - dependency-name: Microting.ItemsPlanningBase
    versions:
    - 2.2.0
    - 2.2.10
    - 2.2.15
    - 2.2.21
    - 2.2.25
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
